import type {StorybookConfig} from "@storybook/nextjs";
import {VanillaExtractPlugin} from "@vanilla-extract/webpack-plugin";

const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const config: StorybookConfig = {
    stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
    addons: [
        "@storybook/addon-onboarding",
        "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@chromatic-com/storybook",
        "@storybook/addon-interactions",
    ],
    framework: {
        name: "@storybook/nextjs",
        options: {},
    },
    webpackFinal(config, options) {
        // Add Vanilla-Extract and MiniCssExtract Plugins
        config.plugins?.push(
            new VanillaExtractPlugin(),
            new MiniCssExtractPlugin()
        );

        // Exclude vanilla extract files from regular css processing
        config.module?.rules?.forEach((rule: any) => {
            if (
                typeof rule !== "string" &&
                rule.test instanceof RegExp &&
                rule.test.test("test.css")
            ) {
                rule.exclude = /\.vanilla\.css$/i;
            }
        });

        config.module?.rules?.push({
            test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
            use: [
                MiniCssExtractPlugin.loader,
                {
                    loader: require.resolve("css-loader"),
                    options: {
                        url: false, // Required as image imports should be handled via JS/TS import statements
                    },
                },
            ],
        });

        return config;
    },
    docs: {
        autodocs: "tag",
    },
    staticDirs: ['../public', { from: '../public/fonts', to: '/fonts' }],
};
export default config;
